services:
  api:
    build: 
      context: ./back
      dockerfile: Dockerfile
    container_name: camera_rental_api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: camera_rental_db
    environment:
      POSTGRES_DB: camera_rental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
